-- create
CREATE TABLE DEPARTMENT (
  ID INTEGER PRIMARY KEY,
  NAME TEXT NOT NULL,
  LOCATION TEXT NOT NULL
);
CREATE TABLE EMPLOYEE (
  ID INTEGER PRIMARY KEY,
  NAME TEXT NOT NULL,
  SALARY INTEGER NOT NULL,
  DEPT_ID INTEGER,
  FOREIGN KEY (DEPT_ID) references DEPARTMENT(ID)
);

-- insert
INSERT INTO DEPARTMENT VALUES (0001, 'Executive', 'Sydney');
INSERT INTO DEPARTMENT VALUES (0002, 'Production', 'Sydney');
INSERT INTO DEPARTMENT VALUES (0003, 'Resources', 'Cape Town');
INSERT INTO DEPARTMENT VALUES (0004, 'Technical', 'Texas');
INSERT INTO DEPARTMENT VALUES (0005, 'Management', 'Paris');

INSERT INTO EMPLOYEE VALUES (0001, 'Candice', 4685, 1);
INSERT INTO EMPLOYEE VALUES (0002, 'Julia', 2559, 2);
INSERT INTO EMPLOYEE VALUES (0003, 'Bob', 4405, 4);
INSERT INTO EMPLOYEE VALUES (0004, 'Scarlet', 2350, 1);
INSERT INTO EMPLOYEE VALUES (0005, 'Ileana', 1151, 4);

-- fetch 
SELECT DEPARTMENT.NAME, COUNT(EMPLOYEE.ID) as "Number of Employees"
FROM DEPARTMENT
LEFT JOIN EMPLOYEE
ON DEPARTMENT.ID = EMPLOYEE.DEPT_ID
group by DEPARTMENT.NAME
ORDER BY COUNT(EMPLOYEE.ID) DESC, DEPARTMENT.NAME;
